version: "2"

services:
  backend:
    # tty: true
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8080:8080"
    links:
      - db

  db:
    image: mongo:latest
    hostname: mongodbserver
    environment:
      - HOME=/data/db
    volumes:
      - D:\Jayaram\python\strApp\volumes:/data/db
    ports:
      - "27017:27017"
volumes:
  static_volume: {}